manifest:
  remotes:
    - name: anoburn
      url-base: https://github.com/anoburn
    - name: zmk-ardux
      url-base: https://github.com/arduxio
  projects:
    - name: zmk
      remote: anoburn
      revision: custom_device_name
      import: app/west.yml
  self:
    path: config
